# vim:ts=2:sw=2:

---
- hosts: localhost
  become: yes
  tasks:
    - name: install dev environment and headers
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - bash-completion
        - build-essential
        - cppcheck
        - clang-8
        - clang-format-8
        - clang-tidy-8
        - clang-tools-8
        - git
        - libgtk-3-dev
        - libsdl2-dev
        - libxcb1-dev
        - neovim
        - x11proto-dev
        - xorg-dev

    - name: install pip3
      apt:
        name: python3-pip

    - name: install golang
      apt:
        name: golang

    - name: install rust
      apt:
        name: cargo

